services:
  api:
    build: .
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://myuser:12345@db:5432/finaldb
    depends_on:
      - db
    networks:
      - app-network
    command: >
      sh -c "python -m alembic upgrade head &&
             python -m uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db:
    image: postgres:15-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=finaldb
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d finaldb"]
      interval: 5s
      timeout: 5s
      retries: 10
  
      
#  migrate:
#    build: .
#    environment:
#      - DATABASE_URL=postgresql://myuser:12345@db:5432/finaldb
#    depends_on:
#      db:
#        condition: service_healthy
#    command: ["alembic", "upgrade", "head"]
#    networks:
#      - app-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./alert_rules.yml:/etc/prometheus/alert_rules.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
