"""init_structure

Revision ID: bcc39fccd1b1
Revises: 
Create Date: 2026-01-14 11:52:59.872617

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'bcc39fccd1b1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
